services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nodejsapp
    networks:
      - nodejsuser-net
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
      #- ./db.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql for database initialization pass in db.sql file
  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy  # to check for healthcheck tags in db configuration
    networks:
      - nodejsuser-net
    ports:
      - "3000:3000"
    env_file: .env
    # environment:
    #   DATABASE_URL: "http://localhost:5432//root:rootpassword@db/nodejsapp"
    command: ["npm", "start"]

networks:
  nodejsuser-net:
    driver: bridge

volumes:
  db-data: