#   --- Stage 1 build: Build Stage  ---

FROM python:3.10-slim as builder
# Set the working directory inside the container
WORKDIR /usr/src/app
# copy from to our courrent code source to working dir
COPY requirements.txt .
# install dependencies
RUN pip install --user --no-cache-dir -r requirements.txt


#   --- Stage 2: Runtime Stage  ---

FROM python:3.10-slim as runtime

WORKDIR /usr/src/app
# Copy the application files into the container
COPY . .
# copy the dependenccies installed in the builder stage
COPY --from=builder /root/.local /root/.local
# Copy the wait-for-it.sh script from the scripts folder
COPY scripts/wait-for-it.sh /usr/src/app/
# Ensure the script has executable permissions
RUN chmod +x /usr/src/app/wait-for-it.sh
# Update Path to include pip binaries installed in the user's directory
ENV PATH="/root/.local/bin:$PATH"

# EXPOSE 8000
# command to run the app
# with app folder in the main file the function app 
# "127.0.0.1" "0.0.0.0" is the same

# Default command to start the app
#CMD [ "uvicorn" , "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]