apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeapi
  labels:
    app: fakeapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fakeapi
  template:
    metadata:
      labels:
        app: fakeapi
    spec:
      containers:
        - name: fakeapi
          image: dfernscap4/fakeapi
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service 
metadata:
  name: fakeapi
spec:
  type: LoadBalancer
  selector:
    app: fakeapi
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000