apiVersion: v1
kind: Service
metadata:
  name:  mybookstoreservice
  namespace: default
spec:
  selector:
    app:  bookstore2
  type:  NodePort
  ports:
  - protocol: TCP
    name: bookstoretestport
    port:  80
    targetPort:  8080