FROM python:3.10-slim
# Set the working directory inside the container
WORKDIR /usr/src/app
# copy from to our courrent code source to working dir
COPY . .
# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD [ "python" , "app.py"]